version: '3'
services:
  postgres:
    image: postgres:14.12
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.db:/var/lib/postgresql/data/pgdata
