name: Prettier

on: workflow_call

permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.8.8
          prettier_options: --check src
          only_changed: True